# Generated by Django 4.1 on 2022-08-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_collecting_coin_alter_collecting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='collecting',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='coin',
            name='tools',
            field=models.ManyToManyField(to='main_app.tool'),
        ),
    ]
